name: PR Checks

on:
  pull_request:

jobs:
  template-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart_name: [
          "svrn-dim-sensor",
          "svrn-dar-sensor",
          "svrn-dar-ranger"
        ]
    steps:
    - name: Install Helm
      uses: azure/setup-helm@v3
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Validate helm chart ${{ matrix.chart_name }} template
      run: |
        helm template ./charts/${{ matrix.chart_name }}
    - name: Run chart ${{ matrix.chart_name }} linter
      run: |
        helm lint ./charts/${{ matrix.chart_name }}
